"""add model details table

Revision ID: 1b3c229f2435
Revises: 16ce1dc047b0
Create Date: 2025-07-21 06:38:43.131468

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b3c229f2435'
down_revision: Union[str, None] = '16ce1dc047b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_info_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('advantages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disadvantages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('use_cases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('papers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('architecture', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_tree', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_info_id'], ['model_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_info_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_details')
    # ### end Alembic commands ###
