"""add guardrails

Revision ID: 6165b3bdcdf4
Revises: 8b1b22af1516
Create Date: 2025-09-01 16:33:32.778280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6165b3bdcdf4'
down_revision: Union[str, None] = '8b1b22af1516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrail_probes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('deprecation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_table('guardrail_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('probe_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uri', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('examples', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('deprecation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('guard_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('scanner_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('modality_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['probe_id'], ['guardrail_probes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uri')
    )
    op.create_index(op.f('ix_guardrail_rules_probe_id'), 'guardrail_rules', ['probe_id'], unique=False)

    sa.Enum('model', 'moderation', name='providercapabilityenum').create(op.get_bind())
    op.add_column('provider', sa.Column('capabilities', postgresql.ARRAY(postgresql.ENUM('model', 'moderation', name='providercapabilityenum', create_type=False)), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guardrail_rules_probe_id'), table_name='guardrail_rules')
    op.drop_table('guardrail_rules')
    op.drop_table('guardrail_probes')

    op.drop_column('provider', 'capabilities')
    sa.Enum('model', 'moderation', name='providercapabilityenum').drop(op.get_bind())
    # ### end Alembic commands ###
