"""add license table and update model_info

Revision ID: 8b1b22af1516
Revises: 1b3c229f2435
Create Date: 2025-07-24 10:36:30.508507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b1b22af1516'
down_revision: Union[str, None] = '1b3c229f2435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('license',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('type_description', sa.Text(), nullable=False),
    sa.Column('type_suitability', sa.String(), nullable=False),
    sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.add_column('model_info', sa.Column('license_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'model_info', 'license', ['license_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_info', type_='foreignkey')
    op.drop_column('model_info', 'license_id')
    op.drop_table('license')
    # ### end Alembic commands ###
