"""add_model_architecture_relationship

Revision ID: e1cf9740a622
Revises: d9b4b3120a93
Create Date: 2025-09-25 07:38:57.608176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1cf9740a622'
down_revision: Union[str, None] = 'd9b4b3120a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_info', sa.Column('model_architecture_class_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_model_info_architecture_class', 'model_info', 'model_architecture_class', ['model_architecture_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_model_info_architecture_class', 'model_info', type_='foreignkey')
    op.drop_column('model_info', 'model_architecture_class_id')
    # ### end Alembic commands ###
